### ISSUE TITLE
Kleiner Vorschlag ;)

### ISSUE THREAD

**Issue by doppelkool** [Whitescan/Whitescan#1]
### **Hey**,

_ändere doch das_:
"Im a Java Developer working one various Projekts in my freetime! Im always looking for new challenges."

_zu dem hier_:
"I'm a Java Developer and in my freetime I work on various projects! If you have any challenge, please contact me or look at my Fiverr-Page: >link<"

Ist komplett nett gemeint und du kannst den "Issue" auch wieder löschen.
Wünsch dir was ;)

**Comment by Whitescan** [comment]
Danke für deinen Vorschlag :)
